namespace DbgCensus.Core.Objects;

/// <summary>
/// Enumerates the various metagate event types.
/// </summary>
public enum MetagameEventDefinition : uint
{
    TRMeltdownAmerish = 147,
    VSMeltdownAmerish = 148,
    NCMeltdownAmerish = 149,
    TRMeltdownEsamir = 150,
    VSMeltdownEsamir = 151,
    NCMeltdownEsamir = 152,
    TRMeltdownHossin = 153,
    VSMeltdownHossin = 154,
    NCMeltdownHossin = 155,
    TRMeltdownIndar = 156,
    VSMeltdownIndar = 157,
    NCMeltdownIndar = 158,
    LowPopCollapseAmerish = 159,
    LowPopCollapseEsamir = 160,
    LowPopCollapseHossin = 161,
    LowPopCollapseIndar = 162,
    NCUnstableMeltdownEsamir = 176,
    NCUnstableMeltdownHossin = 177,
    NCUnstableMeltdownAmerish = 178,
    NCUnstableMeltdownIndar = 179,
    VSUnstableMeltdownEsamir = 186,
    VSUnstableMeltdownHossin = 187,
    VSUnstableMeltdownAmerish = 188,
    VSUnstableMeltdownIndar = 189,
    TRUnstableMeltdownEsamir = 190,
    TRUnstableMeltdownHossin = 191,
    TRUnstableMeltdownAmerish = 192,
    TRUnstableMeltdownIndar = 193,
    OutfitWarsCaptureRelics = 204,
    OutfitWarsPreMatch = 205,
    OutfitWarsRelicsChanging = 206,
    OutfitWarsMatchStart = 207,
    NCMeltdownKoltyr = 208,
    TRMeltdownKoltyr = 209,
    VSMeltdownKoltyr = 210,
    ConquestAmerish = 211,
    ConquestEsamir = 212,
    ConquestHossin = 213,
    ConquestIndar = 214,
    ConquestKoltyr = 215,
    NCMeltdownOshur = 222,
    TRMeltdownOshur = 223,
    VSMeltdownOshur = 224
}
